
  /*******************************************************************
  * PoliceService.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package io.github.froger.instamaterial.ui.utils;

import com.backendless.Backendless;
import com.backendless.async.callback.AsyncCallback;
import java.util.*;


public class PoliceService
{
    static final String SERVICE_NAME = "police";
    static final String SERVICE_VERSION_NAME = "1.0";

    
    public static com.backendless.BackendlessCollection<com.backendless.geo.GeoPoint> getInMap(double nlatitude, double wlongiture, double slatitude, double elongitude, int mapWidth)
    {
        Object[] args = new Object[]{nlatitude, wlongiture, slatitude, elongitude, mapWidth};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getInMap", args, com.backendless.BackendlessCollection.class );
    }
    
    public static void getInMapAsync(double nlatitude, double wlongiture, double slatitude, double elongitude, int mapWidth, AsyncCallback<com.backendless.BackendlessCollection<com.backendless.geo.GeoPoint>> callback)
    {
        Object[] args = new Object[]{nlatitude, wlongiture, slatitude, elongitude, mapWidth};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getInMap", args, com.backendless.BackendlessCollection.class, callback);
    }
    
    public static com.backendless.BackendlessCollection<com.backendless.geo.GeoPoint> getReports(double latitude, double longitude, double radius)
    {
        Object[] args = new Object[]{latitude, longitude, radius};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getReports", args, com.backendless.BackendlessCollection.class );
    }
    
    public static void getReportsAsync(double latitude, double longitude, double radius, AsyncCallback<com.backendless.BackendlessCollection<com.backendless.geo.GeoPoint>> callback)
    {
        Object[] args = new Object[]{latitude, longitude, radius};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getReports", args, com.backendless.BackendlessCollection.class, callback);
    }
    
    public static void report(String userId, byte[] image, double latitude, double longitude, String description)
    {
        Object[] args = new Object[]{userId, image, latitude, longitude, description};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "report", args );
    }
    
    public static void reportAsync(String userId, byte[] image, double latitude, double longitude, String description, AsyncCallback<Object> callback)
    {
        Object[] args = new Object[]{userId, image, latitude, longitude, description};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "report", args, Object.class, callback);
    }
    
}
